name: Build and add binaries to release
on:
  release:
    types:
      - published

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.26' # As we have go toolchain 1.26 specified in go.mod

jobs:
  binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Download cyclonedx-gomod
        uses: CycloneDX/gh-gomod-generate-sbom@v2
        with:
          version: v1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
